version: '3'
services:
  sql-server-db:
    container_name: '${serverName}_DB'
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${BD_password}"
      ACCEPT_EULA: "Y"